services:
  onlinebookstore:
        container_name: onlinebookstore
        build:
            context: onlinebookstore
            dockerfile: Dockerfile
        image: onlinebookstore:latest
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - spring-cloud-network
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      - spring-cloud-network
volumes:
  prom_data:
networks:
    spring-cloud-network:
        driver: bridge
